// Session report export — a self-contained Markdown document of one
// Session (scenario context, stats, analysis, full transcript) that a
// student can submit as practice evidence or keep as a record.
import { Session } from '../types';
import { getScenario } from './sqlite';
import { analyzeConversation } from './analysis';

function formatClock(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export async function buildSessionReport(session: Session): Promise<string> {
  const scenario = await getScenario(session.scenario).catch(() => null);
  const transcript = session.transcript || [];
  const when = session.startTime ? new Date(session.startTime) : null;

  const lines: string[] = [];
  lines.push(`# Practice session report — ${scenario?.name ?? 'Conversation'}`);
  lines.push('');
  if (when) {
    lines.push(`**Date:** ${when.toLocaleDateString()} ${when.toLocaleTimeString()}`);
  }
  if (scenario) {
    lines.push(`**Scenario:** ${scenario.name} (${scenario.difficulty}, ~${scenario.estimatedMinutes} min)`);
    if (scenario.description) lines.push(`**About:** ${scenario.description}`);
  }
  lines.push(`**Duration:** ${formatClock(session.duration ?? 0)}`);
  lines.push('');

  try {
    const a = analyzeConversation(session, transcript);
    lines.push('## Analysis');
    lines.push('');
    lines.push('| Measure | Value |');
    lines.push('| --- | --- |');
    lines.push(`| Fluency score | ${a.fluency.score}/100 |`);
    lines.push(`| Engagement score | ${a.engagement.score}/100 |`);
    lines.push(`| Words spoken | ${a.overall.wordsSpoken} |`);
    lines.push(`| Average response length | ${a.speaking.averageResponseLength.toFixed(1)} words |`);
    lines.push(`| Average response time | ${a.overall.responseTimeAvg.toFixed(1)}s |`);
    lines.push(`| Conversation pace | ${a.overall.conversationPace} |`);
    lines.push(`| Filler words | ${a.speaking.fillerWordCount} (${a.speaking.fillerWordPercentage.toFixed(1)}%) |`);
    if (a.fluency.feedback.length > 0) {
      lines.push('');
      lines.push('### Feedback');
      lines.push('');
      for (const f of a.fluency.feedback) lines.push(`- ${f}`);
    }
    lines.push('');
  } catch {
    // Analysis is best-effort; the transcript is the substance.
  }

  lines.push('## Transcript');
  lines.push('');
  for (const msg of transcript) {
    if (msg.role === 'user') lines.push(`**You:** ${msg.content}`);
    else if (msg.role === 'assistant') lines.push(`**Partner:** ${msg.content}`);
    else continue;
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by Talk Buddy. All practice data stays on the device._');
  lines.push('');
  return lines.join('\n');
}

export async function downloadSessionReport(session: Session): Promise<void> {
  const markdown = await buildSessionReport(session);
  const scenario = await getScenario(session.scenario).catch(() => null);
  const date = session.startTime ? new Date(session.startTime).toISOString().slice(0, 10) : 'session';
  const safeName = (scenario?.name ?? 'practice').replace(/[\/\\:*?"<>|]/g, '-');

  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${safeName} — ${date}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
