// Phase-2 speech benchmark — the go/pivot gate for the sidecar retirement.
//
// Measures, in a real Electron renderer (not Node, not jsdom):
//   STT  — transformers.js whisper-tiny q8, WASM: load time + warm
//          transcription latency over a ~30s utterance, as RTF (real-time
//          factor). Both single-thread (what ships without cross-origin
//          isolation) and, when BENCH_COOP=1 isolation is on, multithreaded.
//   TTS  — kokoro-js (same Kokoro-82M the Speaches path serves) q8: load
//          time + per-sentence synthesis latency vs the TTSPipeline ~1s
//          per-sentence budget.
//
// The STT input is generated by Kokoro itself — a real-speech 30s passage,
// resampled 24kHz→16kHz — so the transcription benchmark exercises real
// phonemes rather than synthetic tones.
//
// Results print as a single `__BENCH_RESULT__ {...}` console line; the
// Electron runner (scripts/bench-electron.mjs) parses it and exits.
// Model files are fetched through a fetch shim from the local mirror
// (public/hf-proxy/, filled by scripts/fetch-bench-models.mjs), keeping the
// run inside CSP and reproducible offline.

import { downsampleTo16k } from '../renderer/turn/vad';

// ---- Gates (from docs/future-work.md phase 2) -------------------------------
const STT_GATE_RTF = 0.2;   // 30s utterance transcribed in ≤ 6s
const TTS_GATE_MS = 1000;   // median sentence synthesis ≤ 1s (TTSPipeline budget)

const STT_MODEL = 'onnx-community/whisper-tiny';
const TTS_MODEL = 'onnx-community/Kokoro-82M-v1.0-ONNX';

const PASSAGE = [
  'Thank you for coming in today. To start, could you walk me through your background ',
  'and tell me what drew you to this role? I would like to hear about the projects you ',
  'are most proud of, how you worked with the team around you, and what you learned ',
  'when things did not go to plan. Take your time — this is a conversation, not a test.',
].join('');

const SENTENCES = [
  'So, tell me a little about yourself and your background.',
  'I led a team of four engineers to deliver the payments migration two weeks ahead of schedule.',
  'That sounds like a great experience. How did you handle the disagreements inside the team?',
];

// ---- Plumbing ---------------------------------------------------------------

const log = (msg: string, cls = '') => {
  console.log(msg);
  const el = document.createElement('div');
  el.className = cls;
  el.textContent = msg;
  document.getElementById('log')!.appendChild(el);
};

// Redirect HF + jsdelivr to the local mirror / node_modules before anything
// dynamic-imports a model runtime. jsdelivr URLs carry a version segment the
// node_modules path does not, so strip it during the rewrite.
const realFetch = window.fetch.bind(window);
window.fetch = ((input: RequestInfo | URL, init?: RequestInit) => {
  const url = typeof input === 'string' ? input : input instanceof Request ? input.url : String(input);
  if (url.startsWith('https://huggingface.co/')) {
    return realFetch('http://localhost:3307/hf-proxy/' + url.slice('https://huggingface.co/'.length), init);
  }
  const jsdelivr = url.match(/^https:\/\/cdn\.jsdelivr\.net\/npm\/(@?[^@/]+)@[^/]+\//);
  if (jsdelivr) {
    return realFetch(`http://localhost:3307/node_modules/${jsdelivr[1]}/` + url.slice(url.match(/^https:\/\/cdn\.jsdelivr\.net\/npm\/[^/]+\//)![0].length), init);
  }
  return realFetch(input as RequestInfo, init);
}) as typeof window.fetch;

window.onerror = (msg) => {
  console.log(`__BENCH_ERROR__ ${msg}`);
};

const median = (xs: number[]): number => {
  const s = [...xs].sort((a, b) => a - b);
  const mid = s.length >> 1;
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
};

// ---- TTS (also produces the STT input) --------------------------------------

interface TtsConfig { label: string; device: 'wasm' | 'webgpu'; dtype: string; }

interface SttResult {
  threads: number;
  loadMs: number;
  runsMs: number[];
  medianMs: number;
  audioSec: number;
  rtf: number;
  text: string;
}

interface TtsResult {
  label: string;
  loadMs: number;
  medianMs: number;
  sentences: Array<{ text: string; ms: number; audioSec: number }>;
}

async function benchTtsConfig(cfg: TtsConfig): Promise<TtsResult> {
  const { KokoroTTS } = await import('kokoro-js');
  const t0 = performance.now();
  const tts = await KokoroTTS.from_pretrained(TTS_MODEL, {
    dtype: cfg.dtype,
    device: cfg.device,
  } as Parameters<typeof KokoroTTS.from_pretrained>[1]);
  const loadMs = performance.now() - t0;
  log(`tts/${cfg.label}: model loaded in ${(loadMs / 1000).toFixed(1)}s`, 'ok');

  const sentences: Array<{ text: string; ms: number; audioSec: number }> = [];
  for (const text of SENTENCES) {
    const t1 = performance.now();
    const audio = await tts.generate(text, { voice: 'af_bella', speed: 1.1 });
    const ms = performance.now() - t1;
    // RawAudio exposes .audio (Float32Array) and .samplingRate; guard the
    // shape so an upstream rename degrades to 0 rather than NaN.
    const rate = (audio as { samplingRate?: number }).samplingRate ?? 24_000;
    const len = (audio as { audio?: Float32Array }).audio?.length ?? 0;
    sentences.push({ text, ms, audioSec: Math.round((len / rate) * 10) / 10 });
    log(`tts/${cfg.label}: sentence in ${(ms / 1000).toFixed(2)}s → ${sentences.at(-1)!.audioSec}s audio — "${text.slice(0, 40)}…"`);
  }

  return { label: cfg.label, loadMs: Math.round(loadMs), sentences, medianMs: Math.round(median(sentences.map((s) => s.ms))) };
}

async function runTtsBench() {
  const results: TtsResult[] = [];
  results.push(await benchTtsConfig({ label: 'wasm-q8', device: 'wasm', dtype: 'q8' }));

  // WebGPU is the reason Electron's Chromium matters here — if the same
  // model flies on the GPU backend, the in-renderer path stays alive.
  const webgpu = (navigator as Navigator & { gpu?: unknown }).gpu;
  if (webgpu) {
    try {
      results.push(await benchTtsConfig({ label: 'webgpu-fp16', device: 'webgpu', dtype: 'fp16' }));
    } catch (err) {
      log(`tts/webgpu-fp16: unavailable — ${err instanceof Error ? err.message : err}`, 'err');
    }
  } else {
    log('tts/webgpu-fp16: navigator.gpu absent — skipping', 'dim');
  }

  // Build the ~30s STT input from real speech: repeat the passage until the
  // rendered audio clears 30 seconds, then trim. Uses the fastest config.
  log('tts: rendering the 30s STT passage…');
  const { KokoroTTS } = await import('kokoro-js');
  const tts = await KokoroTTS.from_pretrained(TTS_MODEL, {
    dtype: 'q8',
    device: 'wasm',
  } as Parameters<typeof KokoroTTS.from_pretrained>[1]);
  let pcm24 = new Float32Array(0);
  const rate = 24_000;
  while (pcm24.length < 31 * rate) {
    const audio = await tts.generate(PASSAGE, { voice: 'am_adam', speed: 1.0 });
    const merged = new Float32Array(pcm24.length + audio.audio.length);
    merged.set(pcm24);
    merged.set(audio.audio, pcm24.length);
    pcm24 = merged;
  }
  const pcm16 = downsampleTo16k(pcm24.slice(0, 30 * rate), rate);

  return { results, sttInput: pcm16 };
}

// ---- STT ---------------------------------------------------------------------

async function runSttBench(pcm16: Float32Array, threads: number): Promise<SttResult> {
  const { pipeline, env } = await import('@huggingface/transformers');
  const wasm = env.backends.onnx.wasm!;
  wasm.numThreads = threads;
  wasm.proxy = false;

  const t0 = performance.now();
  const transcriber = await pipeline('automatic-speech-recognition', STT_MODEL, {
    dtype: 'q8',
    device: 'wasm',
  });
  const loadMs = performance.now() - t0;
  log(`stt(${threads}t): model loaded in ${(loadMs / 1000).toFixed(1)}s`, 'ok');

  // One warmup (first inference allocates buffers / warms JIT), then timed runs.
  await transcriber(pcm16);
  const runsMs: number[] = [];
  let text = '';
  for (let i = 0; i < 2; i++) {
    const t1 = performance.now();
    const out = await transcriber(pcm16);
    runsMs.push(performance.now() - t1);
    text = out.text;
    log(`stt(${threads}t): run ${i + 1} in ${(runsMs.at(-1)! / 1000).toFixed(2)}s — "${text.slice(0, 60)}…"`);
  }

  const audioSec = pcm16.length / 16_000;
  const medianMs = median(runsMs);
  return {
    threads,
    loadMs: Math.round(loadMs),
    runsMs: runsMs.map((ms) => Math.round(ms)),
    medianMs: Math.round(medianMs),
    audioSec: Math.round(audioSec * 10) / 10,
    rtf: Math.round((medianMs / 1000 / audioSec) * 1000) / 1000,
    text: text.slice(0, 160),
  };
}

// ---- Main ---------------------------------------------------------------------

async function main() {
  log(`env: cores=${navigator.hardwareConcurrency} crossOriginIsolated=${String(crossOriginIsolated)}`, 'dim');

  const tts = await runTtsBench();
  const stt: SttResult[] = [];
  stt.push(await runSttBench(tts.sttInput, 1));
  if (crossOriginIsolated && (navigator.hardwareConcurrency || 1) > 1) {
    stt.push(await runSttBench(tts.sttInput, Math.min(4, navigator.hardwareConcurrency)));
  }

  const bestStt = stt.reduce((a, b) => (b.rtf < a.rtf ? b : a));
  const bestTts = tts.results.reduce((a, b) => (b.medianMs < a.medianMs ? b : a));
  const result = {
    env: {
      platform: navigator.platform,
      cores: navigator.hardwareConcurrency,
      crossOriginIsolated,
    },
    stt: stt,
    tts: tts.results,
    gates: {
      sttRtf: { value: bestStt.rtf, limit: STT_GATE_RTF, pass: bestStt.rtf <= STT_GATE_RTF },
      ttsMedianMs: { value: bestTts.medianMs, limit: TTS_GATE_MS, pass: bestTts.medianMs <= TTS_GATE_MS, config: bestTts.label },
    },
  };
  log(`__BENCH_RESULT__ ${JSON.stringify(result)}`);
  const verdict = result.gates.sttRtf.pass && result.gates.ttsMedianMs.pass;
  log(verdict ? 'VERDICT: PASS — proceed to phase 3 (in-renderer providers)' : 'VERDICT: FAIL — pivot to native sidecar', verdict ? 'ok' : 'err');
}

void main().catch((err) => {
  console.log(`__BENCH_ERROR__ ${err instanceof Error ? err.stack : String(err)}`);
});
